markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: lhswei
author: "luhengsi"
email: 609741@163.com
name: "luis's blogs"
url: https://lhswei.github.io
domain: lhswei.github.io
all_categories: [
["program", "软件编程","/posts/program.html"],
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Zhu Hai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
